//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevanthTechTask.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class tblTicket
    { 
       
        public int Id { get; set; }
        [Required]
        public string Userr { get; set; }
        [Required]
        public string Category { get; set; }
        [Required]
        public string ShortDescription { get; set; }
      
        public Nullable<System.DateTime> Datee { get; set; }
        [Required]
        public string AdditionalInfo { get; set; }
        [Required]
        public string RaisedBy { get; set; }
        [Required]
        public string Priorityy { get; set; }
        [Required]
        public string AssignmentType { get; set; }
        [Required]
        public string Statuss { get; set; }
        [Required]
        public string ContactType { get; set; }
        [Required]
        public string AssigneeGroup { get; set; }
      
        public string AssigneeTo { get; set; }


        //public List<SelectListItem> Categories { get; set; }
        //public List<SelectListItem> PriorityList { get; set; }
        //public List<SelectListItem> AssignmentTypes { get; set; }
        //public List<SelectListItem> Statuses { get; set; }
        //public List<SelectListItem> ContactTypes { get; set; }
        //public List<SelectListItem> AssigneeGroups { get; set; }
        //public List<SelectListItem> AssigneeToOptions { get; set; }
    }
}
